type MstProvince = {
  provinceId?: string;
  provinceName?: string;
};

type MstLocation = {
  id?: number;
  siteNetworkId?: number;
  siteNetworkName?: string;
  siteNetworkSeq?: number;
  provinceName?: string;
  locationName?: string;
  address?: string;
  staffOrganize?: string;
  telephoneNumber?: string;
  wan1Provider?: string;
  wan1Cid?: string;
  wan1Speed?: string;
  wan1AsNumber?: string;
  wan1IpWan1Pe?: string;
  wan1IpWan1Ce?: string;
  wan1Subnet?: string;
  wan2Provider?: string;
  wan2Cid?: string;
  wan2Speed?: string;
  wan2AsNumber?: string;
  wan2IpWan1Pe?: string;
  wan2IpWan1Ce?: string;
  wan2Subnet?: string;
  internetCid?: string;
  internetSpeed?: string;
  internetAsNumber?: string;
  internetWanIpAddress?: string;
  internetSubnet?: string;
  cellularSim?: string;
  cellularAr109?: string;
};

type MstTypeRepair = {
  data?: string;
  value?: string;
};

type TrnSiteInformation = {
  siteNetwork?: TrnSiteNetwork;
  sysStatus?: TrnSysStatus;
  sysUser?: TrnSysUser;
  id?: number;
  siteNetworkId?: number;
  siteNetworkName?: string;
  siteNetworkSeq?: number;
  provinceName?: string;
  locationName?: string;
  address?: string;
  staffOrganize?: string;
  telephoneNumber?: string;
  latitude?: string;
  longitude?: string;
  installWan1Team?: null;
  installWan1Telephone?: null;
  installWan2Team?: null;
  installWan2Telephone?: null;
  installInternetTeam?: null;
  installInternetTelephone?: null;
  installCellularTeam?: null;
  installCellularTelephone?: null;
  installDeviceTeam?: null;
  installDeviceTelephone?: null;
  wan1Provider?: string;
  wan1Cid?: string;
  wan1Speed?: string;
  wan1AsNumber?: string;
  wan1IpWan1Pe?: string;
  wan1IpWan1Ce?: string;
  wan1Subnet?: string;
  wan2Provider?: string;
  wan2Cid?: string;
  wan2Speed?: string;
  wan2AsNumber?: string;
  wan2IpWan1Pe?: string;
  wan2IpWan1Ce?: string;
  wan2Subnet?: string;
  internetCid?: string;
  internetSpeed?: string;
  internetAsNumber?: string;
  internetWanIpAddress?: string;
  internetSubnet?: string;
  cellularSim?: string;
  cellularAr109?: string;
  ipLanGateway?: string;
  ipLanSubnet?: string;
  equipmentCpeSwitchMain?: string;
  equipmentSnCpeSwitchMain?: string;
  equipmentCpeSwitchSecondary?: string;
  equipmentSnCpeSwitchSecondary?: string;
  equipmentFirewall2Set?: string;
  equipmentFirewall1Sn?: string;
  equipmentFirewall2Sn?: string;
  equipmentRouter2Set?: string;
  equipmentRouter1Sn?: string;
  equipmentRouter2Sn?: string;
  equipmentWifi1Set?: string;
  equipmentWifiSn?: string;
  equipmentRouter4gSet?: string;
  equipmentRouter4gSn?: string;
  image1?: string;
  image2?: string;
  image3?: string;
  image4?: string;
  image5?: string;
  image6?: string;
  image7?: string;
  image8?: string;
  image9?: string;
  image10?: string;
  image11?: string;
  image12?: string;
  image13?: string;
  image14?: string;
  image15?: string;
  image16?: string;
  image17?: string;
  image18?: string;
  image19?: string;
  image20?: string;
  image21?: string;
  image22?: string;
  image23?: string;
  image24?: string;
  image25?: string;
  image26?: string;
  image27?: string;
  image28?: string;
  createDate?: Date;
  createBy?: string;
  updateDate?: Date;
  updateBy?: string;
  isActive?: boolean;
  mainMaxHour?: number;
  mainMonthlyServiceFee?: number;
  mainFineRateHourPercent?: number;
  mainFineRateHourAmount?: number;
  mainFineRateMinimum?: number;
  secondaryMaxHour?: number;
  secondaryMonthlyServiceFee?: number;
  secondaryFineRateHourPercent?: number;
  secondaryFineRateHourAmount?: number;
  secondaryFineRateMinimum?: number;
  internetMaxHour?: number;
  internetMonthlyServiceFee?: number;
  internetFineRateHourPercent?: number;
  internetFineRateHourAmount?: number;
  internetFineRateMinimum?: number;
  corpnetMaxHour?: number;
  corpnetMonthlyServiceFee?: number;
  corpnetFineRateHourPercent?: number;
  corpnetFineRateHourAmount?: number;
  corpnetFineRateMinimum?: number;
  cellularMaxHour?: number;
  cellularMonthlyServiceFee?: number;
  cellularFineRateHourPercent?: number;
  cellularFineRateHourAmount?: number;
  cellularFineRateMinimum?: number;
  sumFineRatePercent?: number;
  sumPrincipalAmount?: number;
  sumDate?: number;
  sumAmount?: number;
  fileAccept1?: string;
  fileAccept1By?: string;
  fileAccept1Date?: Date;
  fileAccept2?: string;
  fileAccept2By?: string;
  fileAccept2Date?: Date;
  fileAccept3?: string;
  fileAccept3By?: string;
  fileAccept3Date?: Date;
  sysStatusId?: number;
  teamInstallContactName?: string;
  teamInstallContactTel?: string;
  fileApproveName?: string;
  fileApproveSize?: number;
  fileApproveUnitSize?: number;
  sysUserId?: number;
  wan1SpeedTestDownload?: string;
  wan1SpeedTestUpload?: string;
  wan2SpeedTestDownload?: string;
  wan2SpeedTestUpload?: string;
  guid?: string;
  image29?: string;
  image30?: string;
  image31?: string;
  image32?: string;
  image33?: string;
  image34?: string;
  image35?: string;
  image36?: string;
  image37?: string;
  image38?: string;
  image39?: string;
  image40?: string;
  image41?: string;
  image42?: string;
  image43?: string;
  image44?: string;
  image45?: string;
  image46?: string;
  image47?: string;
  image48?: string;
  image49?: string;
  image50?: string;
  image51?: string;
  image52?: string;
  image53?: string;
  image54?: string;
  image55?: string;
  image56?: string;
  image57?: string;
  image58?: string;
  image59?: string;
  image60?: string;
  image61?: string;
  image62?: string;
  image63?: string;
  image64?: string;
  image65?: string;
  image66?: string;
  image67?: string;
  circuitInternet100mbDownload?: string;
  circuitInternet100mbUpload?: string;
  circuit4g20mbDownload?: string;
  circuit4g20mbUpload?: string;
  typeOnsiteValue?: string;
  uploadImage1?: string;
  uploadImage2?: string;
  uploadImage3?: string;
  uploadImage4?: string;
  uploadImage5?: string;
  uploadImage6?: string;
  uploadImage7?: string;
  uploadImage8?: string;
  uploadImage9?: string;
  uploadImage10?: string;
  uploadImage11?: string;
  uploadImage12?: string;
  uploadImage13?: string;
  uploadImage14?: string;
  uploadImage15?: string;
  uploadImage16?: string;
  uploadImage17?: string;
  uploadImage18?: string;
  uploadImage19?: string;
  uploadImage20?: string;
  uploadImage21?: string;
  uploadImage22?: string;
  uploadImage23?: string;
  uploadImage24?: string;
  uploadImage25?: string;
  uploadImage26?: string;
  uploadImage27?: string;
  uploadImage28?: string;
  uploadImage29?: string;
  uploadImage30?: string;
  uploadImage31?: string;
  uploadImage32?: string;
  uploadImage33?: string;
  uploadImage34?: string;
  uploadImage35?: string;
  uploadImage36?: string;
  uploadImage37?: string;
  uploadImage38?: string;
  uploadImage39?: string;
  uploadImage40?: string;
  uploadImage41?: string;
  uploadImage42?: string;
  uploadImage43?: string;
  uploadImage44?: string;
  uploadImage45?: string;
  uploadImage46?: string;
  uploadImage47?: string;
  uploadImage48?: string;
  uploadImage49?: string;
  uploadImage50?: string;
  uploadImage51?: string;
  uploadImage52?: string;
  uploadImage53?: string;
  uploadFileApprove?: string;
};

type TrnSiteNetwork = {
  id?: number;
  name?: string;
  jobWan1?: boolean;
  jobWan2?: boolean;
  jobInternet?: boolean;
  jobCorpnet?: boolean;
  jobCellular?: boolean;
  jobDevice?: boolean;
  createDate?: Date;
  createBy?: string;
  updateDate?: Date;
  updateBy?: string;
  isActive?: boolean;
};

type TrnSysStatus = {
  id?: number;
  nameTh?: string;
  nameEn?: string;
  createDate?: Date;
  createBy?: string;
  updateDate?: Date;
  updateBy?: string;
  isActive?: boolean;
  category?: string;
};

type TrnSysUser = {
  id?: number;
  username?: string;
  password?: string;
  name?: string;
  userGroup?: string;
  createDate?: Date;
  createBy?: string;
  updateDate?: Date;
  updateBy?: string;
  isActive?: boolean;
};

type TrnSumJobRepair = {
  acceptJobToday?: number;
  onProcessJobToday?: number;
  succesJobToday?: number;
  jobAll?: number;
  acceptJobAll?: number;
  onProcessJobAll?: number;
  succesJobAll?: number;
  acceptJobPercent?: number;
  onpProcessJobPercent?: number;
  succesJobPercent?: number;
  outOfSlaAll?: number;
  outOfSlaPercent?: number;
};

// type MstCaseOfFixed = {
//   data?: string;
//   value?: string;
// };

type MstCaseOfIssue = {
  data?: string;
  value?: string;
};

type MstCaseOfIssueSub = {
  data?: string;
  value?: string;
};

type MstFixCase = {
  data?: string;
  value?: string;
};
